# vim:ft=kitty
## name: Breeze_Light
## author: Antigravity
## blurb: Clean modern light theme for Hyprland

# The basic colors
foreground              #232629
background              #fcfcfc
selection_foreground    #232629
selection_background    #bfe2fb

# Cursor colors
cursor                  #0284c7
cursor_text_color       #ffffff

# Kitty window border colors
active_border_color     #0284c7
inactive_border_color   #d3d7dc

# Tab bar colors
active_tab_foreground   #232629
active_tab_background   #ffffff
inactive_tab_foreground #6c757d
inactive_tab_background #e4e7eb

# black
color0 #232629
color8 #6c757d

# red
color1 #dc2626
color9 #ef4444

# green
color2  #16a34a
color10 #22c55e

# yellow
color3  #d97706
color11 #f59e0b

# blue
color4  #0284c7
color12 #38bdf8

# magenta
color5  #7c3aed
color13 #a855f7

# cyan
color6  #0d9488
color14 #14b8a6

# white
color7  #e4e7eb
color15 #ffffff
