font_family         FiraCode Nerd Font
font_size           11.5

# Visual padding & blur
window_padding_width 10
background_opacity  0.85
background_blur     32

# Cursor
cursor_shape        beam
cursor_blink_interval 0.5
cursor_stop_blinking_after 15.0

# Misc
confirm_os_window_close 0

# BEGIN_KITTY_THEME
# VSCode_Dark
include current-theme.conf
# END_KITTY_THEME
