-- Generated by nwg-displays on 2026-05-09 at 12:20:46. Do not edit manually.
-- Converted to Hyprland Lua configuration

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144.15",
    position = "556x1296",
    scale = 1.25,
})

hl.monitor({
    output = "DP-1",
    mode = "1920x1080@119.88",
    position = "2092x1080",
    scale = 1.0,
})
