# ██     ██ ██ ███  ██ ████▄  ▄████▄ ██     ██ ▄█████   ▄████▄ ███  ██ ████▄    
# ██ ▄█▄ ██ ██ ██ ▀▄██ ██  ██ ██  ██ ██ ▄█▄ ██ ▀▀▀▄▄▄   ██▄▄██ ██ ▀▄██ ██  ██   
#  ▀██▀██▀  ██ ██   ██ ████▀  ▀████▀  ▀██▀██▀  █████▀   ██  ██ ██   ██ ████▀    
                                                                                                                                                       
# ██     ██ ▄████▄ █████▄  ██ ▄█▀ ▄█████ █████▄ ▄████▄ ▄█████ ██████ ▄█████ 
# ██ ▄█▄ ██ ██  ██ ██▄▄██▄ ████   ▀▀▀▄▄▄ ██▄▄█▀ ██▄▄██ ██     ██▄▄   ▀▀▀▄▄▄ 
#  ▀██▀██▀  ▀████▀ ██   ██ ██ ▀█▄ █████▀ ██     ██  ██ ▀█████ ██▄▄▄▄ █████▀ 
                                                                                                                               

#windowrulev2 = float, class:^(kitty)$
#windowrulev2 = size 900 600, class:^(kitty)$
#windowrulev2 = center, class:^(kitty)$

#windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
#windowrule = float, class:kitty #sera exibido como janela flutuante

# workspace = WORKSPACE, RULE
# workspace=1,monitor:eDP-1 #fixar uma workpace por padrao no monitor, exemplo: workspace 1 sempre ativa no monitor eDP-1 (notebook)

# Regras para o Applet de Volume GTK (posicionado sob a barra no canto superior direito)
windowrulev2 = float, class:^(audio-applet)$
windowrulev2 = move 100%-380 46, class:^(audio-applet)$
windowrulev2 = pin, class:^(audio-applet)$
windowrulev2 = stayfocused, class:^(audio-applet)$
windowrulev2 = noborder, class:^(audio-applet)$

