# ██     ██ ██ ███  ██ ████▄  ▄████▄ ██     ██ ▄█████   ▄████▄ ███  ██ ████▄    
# ██ ▄█▄ ██ ██ ██ ▀▄██ ██  ██ ██  ██ ██ ▄█▄ ██ ▀▀▀▄▄▄   ██▄▄██ ██ ▀▄██ ██  ██   
#  ▀██▀██▀  ██ ██   ██ ████▀  ▀████▀  ▀██▀██▀  █████▀   ██  ██ ██   ██ ████▀    
                                                                                                                                                       
# ██     ██ ▄████▄ █████▄  ██ ▄█▀ ▄█████ █████▄ ▄████▄ ▄█████ ██████ ▄█████ 
# ██ ▄█▄ ██ ██  ██ ██▄▄██▄ ████   ▀▀▀▄▄▄ ██▄▄█▀ ██▄▄██ ██     ██▄▄   ▀▀▀▄▄▄ 
#  ▀██▀██▀  ▀████▀ ██   ██ ██ ▀█▄ █████▀ ██     ██  ██ ▀█████ ██▄▄▄▄ █████▀ 
                                                                                                                               

#windowrulev2 = float, class:^(kitty)$
#windowrulev2 = size 900 600, class:^(kitty)$
#windowrulev2 = center, class:^(kitty)$

#windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
#windowrule = float, class:kitty # will be displayed as floating window

# workspace = WORKSPACE, RULE
# workspace=1,monitor:eDP-1 # bind a default workspace to monitor, e.g.: workspace 1 always active on eDP-1 (laptop)

# Rules for GTK Applets (positioned under the bar or centered via script)
windowrule = match:class ^(volume-applet|calendar-applet|wifi-applet|bluetooth-applet|power-applet|session-applet|wallpaper-applet).*$, float on
windowrule = match:class ^(volume-applet|calendar-applet|wifi-applet|bluetooth-applet|power-applet|session-applet|wallpaper-applet).*$, pin on
windowrule = match:class ^(wallpaper-applet).*$, center on
